/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_secundarios;

import conexion.conexion;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author GynRaider
 */
public class modificarProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form modificarProveedor
     */
    Connection con;
    
    public void limpiar(){
        jComboBox1.setEnabled(true);
        numero.setEnabled(true);
        nombreProveedor.setEnabled(false);
        celularProveedor.setEnabled(false);
        docProveedor.setEnabled(false);
        direccionProveedor.setEnabled(false);
        correoProveedor.setEnabled(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
        
        jComboBox1.setSelectedIndex(0);
        codigoProveedor.setText("");
        numero.setText("");
        nombreProveedor.setText("");
        celularProveedor.setText("");
        docProveedor.setText("");
        direccionProveedor.setText("");
        correoProveedor.setText("");
    }
    public modificarProveedor() {
        initComponents();
        jButton3.setMnemonic(KeyEvent.VK_X);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        celularProveedor = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        direccionProveedor = new javax.swing.JTextField();
        correoProveedor = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        docProveedor = new javax.swing.JTextField();
        nombreProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Buscar por:");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Nombre ");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 81, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Celular");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 112, -1, -1));

        celularProveedor.setEnabled(false);
        celularProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularProveedorActionPerformed(evt);
            }
        });
        jPanel10.add(celularProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 110, 116, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Direccion");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 146, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Correo");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 177, -1, -1));

        direccionProveedor.setEnabled(false);
        jPanel10.add(direccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 144, 304, -1));

        correoProveedor.setEnabled(false);
        correoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoProveedorActionPerformed(evt);
            }
        });
        jPanel10.add(correoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 175, 304, -1));
        jPanel10.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 13, 120, 24));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código de Proveedor", "Número de documento" }));
        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Documento");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 113, -1, -1));

        docProveedor.setEnabled(false);
        docProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docProveedorActionPerformed(evt);
            }
        });
        jPanel10.add(docProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 110, 93, -1));

        nombreProveedor.setEnabled(false);
        jPanel10.add(nombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 79, 304, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Código");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 51, -1, -1));

        codigoProveedor.setEnabled(false);
        jPanel10.add(codigoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 48, 75, -1));
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 210));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 420, 208));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 42, -1, -1));

        jButton2.setText("Guardar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 42, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 42, -1, -1));

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 42, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 230, 420, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Captura.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 500, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con = conexion.conectar();
        
        String 
                cod_doc = numero.getText(),
                codProveedor,nombre, direccion, correo,
                buscar = jComboBox1.getSelectedItem().toString(),
                sql;
        
        int celular, documento;
        
        if (cod_doc.equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese un documento o código del proveedor");
        } else {
            try {
                if (buscar.equals("Código de Proveedor")) {
                    sql  = "select * from proveedores where codProveedor  = '"+cod_doc+"'";
                } else {
                    sql  = "select * from proveedores where documento  = '"+cod_doc+"'";
                }
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Proveedor encontrado");

                    codProveedor = rs.getString("codProveedor");
                    nombre = rs.getString("nombre");
                    documento = rs.getInt("documento");
                    direccion = rs.getString("direccion");
                    correo = rs.getString("correo");
                    celular = rs.getInt("celular");

                    jComboBox1.setEnabled(false);
                    numero.setEnabled(false);
                    nombreProveedor.setEnabled(true);
                    celularProveedor.setEnabled(true);
                    docProveedor.setEnabled(true);
                    direccionProveedor.setEnabled(true);
                    correoProveedor.setEnabled(true);
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(true);

                    codigoProveedor.setText(codProveedor);
                    nombreProveedor.setText(nombre);
                    celularProveedor.setText(Integer.toString(celular));
                    docProveedor.setText(Integer.toString(documento));
                    direccionProveedor.setText(direccion);
                    correoProveedor.setText(correo);
                }else{
                    JOptionPane.showMessageDialog(null,"El proveedor no existe o el número ingresado es incorrecto");
                }
                rs.close();
                st.close();
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void celularProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularProveedorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        con = conexion.conectar();
        
        String
                codProv = codigoProveedor.getText(),
                nombre = nombreProveedor.getText(),
                direccion = direccionProveedor.getText(),
                correo = correoProveedor.getText(),
                celular = celularProveedor.getText(),
                documento = docProveedor.getText();

        try {
            CallableStatement cst = con.prepareCall("Call actualizar_proveedor(?,?,?,?,?,?)");
            cst.setString(1,codProv);
            cst.setString(2,nombre);
            cst.setInt(3,Integer.parseInt(documento));
            cst.setString(4,direccion);
            cst.setString(5,correo);
            cst.setInt(6,Integer.parseInt(celular));
            cst.execute();
            cst.close();
            limpiar();
            
            JOptionPane.showMessageDialog(null,"Datos del proveedor actualizados");

            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void docProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docProveedorActionPerformed

    private void correoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celularProveedor;
    private javax.swing.JTextField codigoProveedor;
    private javax.swing.JTextField correoProveedor;
    private javax.swing.JTextField direccionProveedor;
    private javax.swing.JTextField docProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField nombreProveedor;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
