/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_secundarios;

import Atxy2k.CustomTextField.RestrictedTextField;
import conexion.conexion;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author GynRaider
 */
public class nuevoempleadosalmacen extends javax.swing.JInternalFrame {
private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null; 
    /**
     * Creates new form nuevoempleados
     */
    public nuevoempleadosalmacen() {
          ocultarBarraTitulo() ;
        initComponents();
        
        
         RestrictedTextField nc = new RestrictedTextField(nombreEmpleado); 
           nc.setLimit(20);
           
           RestrictedTextField ac = new RestrictedTextField(apellidoEmpleado); 
           ac.setLimit(20);
            RestrictedTextField dc = new RestrictedTextField(docEmpleado); 
           dc.setLimit(8);
           dc.setOnlyNums(true);
           
           RestrictedTextField cd = new RestrictedTextField(celularEmpleado); 
           cd.setLimit(9);
           cd.setOnlyNums(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTF_Codigo = new javax.swing.JTextField();
        nombreEmpleado = new javax.swing.JTextField();
        apellidoEmpleado = new javax.swing.JTextField();
        sexoEmpleado = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        docEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        celularEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        usuarioEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipoEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        JBT_Limpiar = new javax.swing.JButton();
        btnGuardad = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("SISTEMA DE INGRESO DE EMPLEADOS DEL ALMACEN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID Empleado :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Apellidos:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 87, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Sexo :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 160, -1, -1));

        JTF_Codigo.setEditable(false);
        JTF_Codigo.setText("Autogenerado");
        JTF_Codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(JTF_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 14, 115, -1));

        nombreEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 51, 484, -1));

        apellidoEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(apellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 87, 484, -1));

        sexoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexoEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULINO", "FEMENINO", "OTROS" }));
        sexoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(sexoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 154, 173, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Documento de Identidad : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 14, -1, -1));
        jPanel2.add(docEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 13, 185, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Celular : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 160, -1, -1));
        jPanel2.add(celularEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 159, 121, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nombre de usuario:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, -1, -1));
        jPanel2.add(usuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 123, 125, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tipo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 126, -1, -1));

        tipoEmpleado.setEditable(false);
        tipoEmpleado.setText("Empleado de Almacén");
        jPanel2.add(tipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 123, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mchael\\Documents\\NetBeansProjects\\Libreria_GyG\\src\\fondo\\VL.jpg")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 670, 232));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logout_Icon_32.png"))); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 25, -1, -1));

        JBT_Limpiar.setBackground(new java.awt.Color(153, 153, 153));
        JBT_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        JBT_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Paint tools.png"))); // NOI18N
        JBT_Limpiar.setText("LIMPIAR");
        JBT_Limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBT_Limpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        JBT_Limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBT_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_LimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(JBT_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 14, -1, 72));

        btnGuardad.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardad.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnGuardad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Floppy disk.png"))); // NOI18N
        btnGuardad.setText("GUARDAR");
        btnGuardad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardad, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 18, -1, 68));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mchael\\Documents\\NetBeansProjects\\Libreria_GyG\\src\\fondo\\VL.jpg")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 326, 550, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Captura.PNG"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 700, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadActionPerformed
        String
                nombre = docEmpleado.getText(),
                apellido = apellidoEmpleado.getText(),
                usuario = usuarioEmpleado.getText(),
                sexo = sexoEmpleado.getSelectedItem().toString(),
                documento = docEmpleado.getText(),
                celular = celularEmpleado.getText();
        
        Connection cnn;
        
        cnn = conexion.conectar();
        
        if (nombre.equals("")||apellido.equals("")||usuario.equals("")||sexo.equals("")||documento.equals("")||celular.equals("")) {
            JOptionPane.showMessageDialog(null,"Por favor, complete todos los campos.");
        } else {
            try {
                Statement st = cnn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM empleado_almacen WHERE documento='"+documento+"'");
                rs.last();
                
                int encontrado = rs.getRow();

                if (encontrado==1) {
                    JOptionPane.showMessageDialog(null,"Documento ya existente. Consulte la base de datos.");
                    st.close();
                    rs.close();
                } else {
                    try {
                        CallableStatement cst = cnn.prepareCall("CALL insertar_empleado_almacen(?,?,?,?,?,?)");
                        cst.setString(1,nombre);
                        cst.setString(2,apellido);
                        cst.setString(3,usuario);
                        cst.setString(4,sexo);
                        cst.setInt(5,Integer.parseInt(documento));
                        cst.setInt(6,Integer.parseInt(celular));
                        cst.execute();
                        JOptionPane.showMessageDialog(null,"Nuevo encargado de almacén ingresado.");

                        try {
                            Statement st2 = cnn.createStatement();
                            ResultSet rs2 = st2.executeQuery("SELECT * FROM empleado_almacen WHERE documento='"+documento+"'");
                            rs2.last();
                        
                            int encontrado2 = rs2.getRow();
                            
                            if (encontrado2 == 1) {
                                CallableStatement cst2 = cnn.prepareCall("CALL insertar_cuentaUsuario(?,?,?)");
                                cst2.setString(1,usuario);
                                cst2.setString(2,rs2.getString("id_empleadoalmacen"));
                                cst2.setString(3,tipoEmpleado.getText());
                                cst2.execute();
                                
                                JOptionPane.showMessageDialog(null,rs2.getString("id_empleadoalmacen"));
                                st2.close();
                                rs2.close();
                            } else {
                                JOptionPane.showMessageDialog(null,"Corrige esta mierda!");
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null,e);
                        }                        
                        rs.close();
                        st.close();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null,e);
                    }   
                }
                
                cnn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_btnGuardadActionPerformed

    private void JBT_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_LimpiarActionPerformed
        docEmpleado.setText("");
        apellidoEmpleado.setText("");
        docEmpleado.setText("");
        celularEmpleado.setText("");
    }//GEN-LAST:event_JBT_LimpiarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sexoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_Limpiar;
    private javax.swing.JTextField JTF_Codigo;
    private javax.swing.JTextField apellidoEmpleado;
    private javax.swing.JButton btnGuardad;
    private javax.swing.JTextField celularEmpleado;
    private javax.swing.JTextField docEmpleado;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JComboBox sexoEmpleado;
    private javax.swing.JTextField tipoEmpleado;
    private javax.swing.JTextField usuarioEmpleado;
    // End of variables declaration//GEN-END:variables
public void ocultarBarraTitulo()
{ 
Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
dimBarra = Barra.getPreferredSize(); 
Barra.setSize(0,0); 
Barra.setPreferredSize(new Dimension(0,0)); 
repaint(); 
}

}
