/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_secundarios;

import Atxy2k.CustomTextField.RestrictedTextField;
import com.sun.awt.AWTUtilities;
import conexion.conexion;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.Calendar;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author GynRaider
 */

public class nuevoCliente extends javax.swing.JInternalFrame {
    
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null; 
 
    Connection cnn;
    /**
     * Creates new form nuevoCliente
     */
    public nuevoCliente() {
        
            
        ocultarBarraTitulo() ;
//        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
//         
        initComponents();
        
        
        
       
        try {
            cnn = conexion.conectar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"error al conectar a la base de datos");
        }

           RestrictedTextField nc = new RestrictedTextField(nombreCliente); 
           nc.setLimit(40);
           
           RestrictedTextField ac = new RestrictedTextField(apellidoCliente); 
           ac.setLimit(40);
           
           RestrictedTextField rc = new RestrictedTextField(docCliente); 
           rc.setLimit(8);
           rc.setOnlyNums(true);
           RestrictedTextField cc = new RestrictedTextField(correoCliente); 
           cc.setLimit(50);
           
            RestrictedTextField rt = new RestrictedTextField(tlfCliente); 
           rt.setLimit(9);
           
           rt.setOnlyNums(true);
           
           RestrictedTextField dc = new RestrictedTextField(dirCliente); 
           dc.setLimit(50);
          
               
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        tlfCliente = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        dirCliente = new javax.swing.JTextField();
        correoCliente = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        docCliente = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        apellidoCliente = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        rucCliente = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        sexoCliente = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        nacCliente = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JBT_Limpiar = new javax.swing.JButton();
        btnGuardad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Telefono :");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        tlfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tlfClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tlfClienteKeyTyped(evt);
            }
        });
        jPanel2.add(tlfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 16, 130, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Direccion :");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 48, -1, -1));
        jPanel2.add(dirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 47, 315, -1));
        jPanel2.add(correoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 80, 315, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Correo :");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 78, -1, -1));

        jLabel1.setText("(opcional)");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 19, -1, -1));

        jLabel2.setText("(opcional)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 83, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mchael\\Documents\\NetBeansProjects\\Libreria_GyG\\src\\fondo\\VL.jpg")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 130));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 508, 120));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("ID Cliente :");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Documento Identidad :");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 14, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setText("Autogenerado");
        txtCodigo.setEnabled(false);
        jPanel10.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 16, 107, -1));

        docCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                docClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                docClienteKeyTyped(evt);
            }
        });
        jPanel10.add(docCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 16, 138, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Nombres :");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 47, -1, -1));
        jPanel10.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 49, 408, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Apellidos :");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 80, -1, -1));

        apellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoClienteActionPerformed(evt);
            }
        });
        jPanel10.add(apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 82, 407, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("RUC");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel10.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 109, -1, -1));

        rucCliente.setEnabled(false);
        jPanel10.add(rucCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 115, 121, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Sexo:");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 113, -1, -1));

        sexoCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        sexoCliente.setSelectedIndex(-1);
        sexoCliente.setToolTipText("");
        jPanel10.add(sexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 115, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Fecha Nacimiento:");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 150, -1, -1));

        nacCliente.setToolTipText("");
        nacCliente.setDateFormatString("yyyy/MM/dd");
        jPanel10.add(nacCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 126, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mchael\\Documents\\NetBeansProjects\\Libreria_GyG\\src\\fondo\\VL.jpg")); // NOI18N
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 190));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 510, 190));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setText("SISTEMA DE INGRESO CLIENTES");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logout_Icon_32.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 182, 81, -1));

        JBT_Limpiar.setBackground(new java.awt.Color(153, 153, 153));
        JBT_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        JBT_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Paint tools.png"))); // NOI18N
        JBT_Limpiar.setText("LIMPIAR");
        JBT_Limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBT_Limpiar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        JBT_Limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBT_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(JBT_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 92, -1, 72));

        btnGuardad.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardad.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnGuardad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Floppy disk.png"))); // NOI18N
        btnGuardad.setText("GUARDAR");
        btnGuardad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardad, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 18, -1, 68));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mchael\\Documents\\NetBeansProjects\\Libreria_GyG\\src\\fondo\\VL.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 260));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 117, 130, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Captura.PNG"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadActionPerformed
        int
                dni,
                celular=0,
                dia, mes, año,
                sexofail = sexoCliente.getSelectedIndex();

        String
                nombre = nombreCliente.getText(),
                apellido = apellidoCliente.getText(),
                sexo,
                ruc = rucCliente.getText(),
                direccion = dirCliente.getText(),
                email = correoCliente.getText(),
                fecha;
        
        if (nombre.equals("") || apellido.equals("") || direccion.equals("") || sexofail == -1 || nacCliente.getDate()==null || docCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Complete los campos necesarios");
        } else {
            
            dia = nacCliente.getCalendar().get(Calendar.DAY_OF_MONTH);
            mes = nacCliente.getCalendar().get(Calendar.MONTH);
            año = nacCliente.getCalendar().get(Calendar.YEAR);
            fecha = año + "-" + mes + "-" + dia;

            if(sexoCliente.getSelectedItem().equals("masculino")){
                sexo = "M";
            }else{
                sexo = "F";
            }
            
            dni = Integer.parseInt(docCliente.getText());
            
            if (!tlfCliente.getText().equals("")) {
                celular = Integer.parseInt(tlfCliente.getText());
            }
                                    
            try {
                Statement st = cnn.createStatement();
                ResultSet rs = st.executeQuery("Select * from personas where DNI = "+dni);
                rs.last();
                
                int found = rs.getRow();
                
                if (found == 1) {
                    JOptionPane.showMessageDialog(null,"El documento ya existe en la base de datos");
                } else {
                    try {
                        //Insertar registro a la tabla personas
                        cnn = conexion.conectar();

                        CallableStatement cst = cnn.prepareCall("Call insertar_personas(?,?,?,?,?,?,?,?,?)");
                        cst.setString(1,nombre);
                        cst.setString(2,apellido);
                        cst.setInt(3,dni);
                        cst.setString(4,sexo);
                        cst.setString(5,fecha);
                        cst.setString(6,direccion);
                        
                        if (tlfCliente.getText().isEmpty()) {
                            cst.setNull(7,Types.INTEGER);
                        } else {
                            cst.setInt(7,celular);
                        }
                        
                        cst.setString(8,email); 
                        cst.setString(9,"0");
                        cst.execute();

                        JOptionPane.showMessageDialog(null,"Registrado correctamente");

        //              Insertar registro a la tabla clientes
                        Statement st2 = cnn.createStatement();
                        ResultSet rs2 = st2.executeQuery("Select * from personas where DNI = "+dni);
                        rs2.last();

                        int encontrado = rs2.getRow();

                        if (encontrado == 1) {
                            String codPersona = rs2.getString("codPersona");

                            try {
                                CallableStatement cliente = cnn.prepareCall("Call insertar_cliente(?,?)");
                                cliente.setString(1,codPersona);
                                if (jCheckBox1.isSelected()) {
                                    cliente.setString(2,ruc);
                                } else {
                                    cliente.setString(2,"Sin ruc");
                                }
                                cliente.execute();
                                st.close();
                                rs.close();
                                rs2.close();
                                st2.close();
                            } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null,"Hubo un problema al registrar en la tabla cliente" +e);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null,"No se encontró el dni en la tabla personas");
                        }


                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null,e);
                    }
                    
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Hubo un problema al registrar en la tabla personas" + e);
            }
        }
        
    }//GEN-LAST:event_btnGuardadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBT_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT_LimpiarActionPerformed
        nombreCliente.setText("");
        apellidoCliente.setText("");
        dirCliente.setText("");
        correoCliente.setText("");
        tlfCliente.setText("");  
        docCliente.setText("");
    }//GEN-LAST:event_JBT_LimpiarActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
          
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
     
    }//GEN-LAST:event_jPanel3MouseDragged

    private void docClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docClienteKeyPressed

    }//GEN-LAST:event_docClienteKeyPressed

    private void tlfClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlfClienteKeyPressed
        
    }//GEN-LAST:event_tlfClienteKeyPressed

    private void docClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_docClienteKeyTyped

    }//GEN-LAST:event_docClienteKeyTyped

    private void tlfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlfClienteKeyTyped

    }//GEN-LAST:event_tlfClienteKeyTyped

    private void apellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoClienteActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            rucCliente.setEnabled(true);
        }else{
            rucCliente.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

public void ocultarBarraTitulo()
{ 
Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
dimBarra = Barra.getPreferredSize(); 
Barra.setSize(0,0); 
Barra.setPreferredSize(new Dimension(0,0)); 
repaint(); 
}
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT_Limpiar;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JButton btnGuardad;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JTextField dirCliente;
    private javax.swing.JTextField docCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser nacCliente;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField rucCliente;
    private javax.swing.JComboBox sexoCliente;
    private javax.swing.JTextField tlfCliente;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

}
