/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_secundarios;

import Atxy2k.CustomTextField.RestrictedTextField;
import Formularios_principales.Frmadm;
import Formularios_principales.login;
import conexion.conexion;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joel Sanchez
 */
public class nuevasVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form nuevasVentas
     */
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null; 
    public nuevasVentas() {
        initComponents();
        ocultarBarraTitulo();
        Calendar c2 = new GregorianCalendar();
        jDateChooser2.setCalendar(c2);

    }
    
    public static void updateTextField(String t, int c){
        idProducto.setText(t);
        jButton8.doClick();
        jSpinner2.setValue(c);
        btnNuevo.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_codVendedor = new javax.swing.JTextField();
        txt_nombreVendedor = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codCliente = new javax.swing.JTextField();
        npCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dirCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        celularCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        docCliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        PanelNota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroventa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        igv = new javax.swing.JTextField();
        totalV = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        recogeAlmacen = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        idProducto = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        precioProducto = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton8 = new javax.swing.JButton();
        nombreProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Fecha :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText(" Vendedor :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        txt_codVendedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(txt_codVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 88, 71, -1));

        txt_nombreVendedor.setEditable(false);
        txt_nombreVendedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(txt_nombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 88, 193, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel41.setText("LIBRERIA G & G ");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 13, -1, -1));
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 61, 142, -1));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 87, -1, 25));

        jLabel19.setText("jLabel13");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -2, 480, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 460, 120));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cliente :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        codCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(codCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 14, 80, -1));

        npCliente.setEditable(false);
        npCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(npCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 14, 244, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Documento:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 43, -1, -1));

        dirCliente.setEditable(false);
        dirCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(dirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 72, 417, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefono :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 43, -1, -1));

        celularCliente.setEditable(false);
        celularCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(celularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 44, 148, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Direccion : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));

        docCliente.setEditable(false);
        docCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(docCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 44, 128, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 14, -1, -1));

        jLabel14.setText("jLabel13");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -2, 550, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 530, 100));

        PanelNota.setBackground(new java.awt.Color(102, 102, 102));
        PanelNota.setForeground(new java.awt.Color(153, 153, 153));
        PanelNota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NUMERO DE VENTA");
        PanelNota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 160, 29));

        numeroventa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numeroventa.setText("Autogenerado");
        PanelNota.add(numeroventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 13, 206, 29));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/VL.jpg"))); // NOI18N
        PanelNota.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -2, 430, 70));

        jPanel1.add(PanelNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 410, 60));

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logout_Icon_32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO U", "SUBTOTAL"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, 899, 232));

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Valor de Venta :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("IGV :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 18, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Monto IGV :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 18, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Total :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 18, -1, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.setText("18");
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 17, 51, -1));

        igv.setEditable(false);
        igv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 17, 88, -1));

        totalV.setEditable(false);
        totalV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVActionPerformed(evt);
            }
        });
        jPanel5.add(totalV, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 17, 95, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 17, 85, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Descuento:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 18, -1, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setText("0");
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 17, 53, 23));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("%");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 18, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("%");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 18, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(248, 221, 50));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setText("Cancelado");
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 46, -1, -1));

        recogeAlmacen.setText("Recoge en el almacén");
        jPanel5.add(recogeAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 43, -1, 30));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 540, 80));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -2, 540, 80));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 307, 996, -1));

        btnNuevo.setBackground(new java.awt.Color(204, 255, 204));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Badge plus.png"))); // NOI18N
        btnNuevo.setEnabled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 69, -1, 51));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Badge multiply.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 126, -1, 53));

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Floppy disk.png"))); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 248, -1, 53));

        jPanel12.setBackground(new java.awt.Color(255, 153, 102));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setText("Producto :");
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        idProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProductoActionPerformed(evt);
            }
        });
        jPanel12.add(idProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 15, 75, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("Precio Unitario :");
        jPanel12.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 13, -1, -1));

        precioProducto.setEditable(false);
        jPanel12.add(precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 15, 71, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setText("Cantidad :");
        jPanel12.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 13, -1, -1));
        jPanel12.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 15, 45, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 14, -1, -1));

        nombreProducto.setEditable(false);
        jPanel12.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 15, 297, -1));

        jLabel2.setText("S/.");
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 18, -1, -1));
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, -2, 580, 70));

        jLabel21.setText("jLabel13");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -2, 430, 70));

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 996, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Refresh (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 185, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 1010, -1));

        jLabel12.setAutoscrolls(true);
        jLabel12.setFocusCycleRoot(true);
        jLabel12.setFocusTraversalPolicyProvider(true);
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        int c = Integer.parseInt(jSpinner2.getValue().toString());
        double montotal=0,
                p = Double.parseDouble(precioProducto.getText());
        
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        
        if(nombreProducto.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese código del producto");
        }else{
            if(c==0){
                JOptionPane.showMessageDialog(null,"Ingrese una cantidad");
            }else{
                btnNuevo.setEnabled(false);
                btnEliminar.setEnabled(true);
                tabla.addRow( new Object[] {idProducto.getText(), nombreProducto.getText(),c,precioProducto.getText()} );
                idProducto.setText("");
                nombreProducto.setText("");
                jSpinner2.setValue(0);
                precioProducto.setText("");
                
                try {
                    for (int i = 0; i <= jTable1.getRowCount(); i++) {
                    String subto;
                    int 
                            can =  (int) jTable1.getValueAt(i,2);
                    double 
                            preciou = Double.parseDouble((String) jTable1.getValueAt(i,3));
                    
                    subto = Double.toString(preciou*can);
                    
                    montotal = montotal + (preciou*can);
                    jTable1.setValueAt(subto,i,4);
                }
                } catch (Exception e) {
                }
                
                jTextField1.setText(Double.toString(Math.round(montotal*100)/100));
                
                double totaligv, total,descuento;
                totaligv = montotal * Double.parseDouble(jTextField12.getText())/100;
                descuento = montotal * Double.parseDouble(jTextField2.getText())/100;
                total = montotal + totaligv - descuento;
                
                igv.setText(Double.toString(Math.round(totaligv*100)/100));
                totalV.setText(Double.toString(Math.round(total*100)/100));
                
                btnGuardar.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProductoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con;
        con = conexion.conectar();
        
        String codcliente,
                nombrecliente,
                apellidocliente,
                dircliente;
        int
                doccliente,
                celularcliente;
        
        try {
            CallableStatement cst = con.prepareCall("Call buscar_cliente(?,?,?,?,?,?,?,?)");
            
            cst.setString(1,codCliente.getText());
            cst.registerOutParameter(2, java.sql.Types.VARCHAR);
            cst.registerOutParameter(3, java.sql.Types.VARCHAR);
            cst.registerOutParameter(4, java.sql.Types.VARCHAR);
            cst.registerOutParameter(5, java.sql.Types.VARCHAR);
            cst.registerOutParameter(6, java.sql.Types.INTEGER);
            cst.registerOutParameter(7, java.sql.Types.INTEGER);
            cst.registerOutParameter(8, java.sql.Types.VARCHAR);
            cst.execute();
            
            nombrecliente = cst.getString(4);
            apellidocliente = cst.getString(5);
            doccliente = cst.getInt(6);
            celularcliente = cst.getInt(7);
            dircliente = cst.getString(8);            
            
            npCliente.setText(nombrecliente+" "+apellidocliente);
            docCliente.setText(Integer.toString(doccliente));
            if(celularcliente == 0){
                celularCliente.setText("Sin número");
            }else{
                celularCliente.setText(Integer.toString(celularcliente));
            }
            dirCliente.setText(dircliente);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Connection con;
        con = conexion.conectar();
        
        String idproducto,
                nombreproducto;
        int
                cantidadproducto;
        
        double precioproducto;
        
        if(idProducto.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese código del producto");
        }else{
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM almacen where codProducto='"+idProducto.getText()+"'");

                if (rs.next()) {
                    nombreproducto = rs.getString("nombre");
                    precioproducto = rs.getDouble("precio");
                    cantidadproducto = rs.getInt("stock");

                    nombreProducto.setText(nombreproducto);
                    precioProducto.setText(Double.toString(precioproducto));
                }else{
                    JOptionPane.showMessageDialog(null,"Producto no registrado");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Error conectando con la base de datos /n"+e);
            }
        }
        
        
        btnNuevo.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        
        double montotal = 0;
        int fila = jTable1.getSelectedRow();
        
        if(fila>=0){
            tabla.removeRow(fila);
        }
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            double
                    nuevovalor = Double.parseDouble((String) jTable1.getValueAt(i,4));
            
            montotal +=  nuevovalor;
        }
        
        jTextField1.setText(Double.toString(Math.round(montotal*100)/100));
        
        double totaligv, total,descuento;
        totaligv = montotal * Double.parseDouble(jTextField12.getText())/100;
        descuento = montotal * Double.parseDouble(jTextField2.getText())/100;
        total = montotal + totaligv - descuento;

        igv.setText(Double.toString(Math.round(totaligv*100)/100));
        totalV.setText(Double.toString(Math.round(total*100)/100));
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Connection con;
        con = conexion.conectar();
        
        String idcliente,idvendedor,fecha,canc;
        
        int dia,mes,año;
        dia=jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH);
        mes=jDateChooser2.getCalendar().get(Calendar.MONTH);
        año=jDateChooser2.getCalendar().get(Calendar.YEAR);
        
        fecha = año + "-" + mes + "-" + dia;
        
        if(jCheckBox1.isSelected()==true){
            canc = "Cancelado";
        }else{
            canc = "Por Cancelar";
        }
        
        idcliente = codCliente.getText();
        idvendedor = txt_codVendedor.getText();
        
        
        if (txt_nombreVendedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese código del empleado");
        } else {
            if (npCliente.getText().equals("")) {
                int result = JOptionPane.showConfirmDialog(null,"No se ha ingresado un cliente.\n¿Seguro que desea realizar la operación?",null, JOptionPane.YES_NO_OPTION);
                
                if(result == JOptionPane.YES_OPTION) {
                    try {
                         CallableStatement cst = con.prepareCall("CALL insertar_registro_ventas(?,?,?,?)");
                         cst.setString(1,"NoRegistro");
                         cst.setString(2,idvendedor);
                         cst.setString(3,fecha);
                         cst.setString(4,canc);
                         cst.execute();
                         
                         Statement st = con.createStatement();
                         ResultSet rs = st.executeQuery("SELECT * FROM registro_ventas WHERE idPersonalVentas ='"+idvendedor+"'");
                         rs.last();
                         
                         String idregistroventa = rs.getString("codRegVentas");
                         
                         for (int i = 0; i < jTable1.getRowCount(); i++) {
                             try (CallableStatement cst2 = con.prepareCall("CALL insertar_detalle_venta(?,?,?,?)")) {
                                 cst2.setString(1,idregistroventa);
                                 cst2.setString(2, (String) jTable1.getValueAt(i,0));
                                 cst2.setInt(3, (int) jTable1.getValueAt(i,2));
                                 cst2.setDouble(4,Double.parseDouble((String) jTable1.getValueAt(i,3)));
                                 cst2.execute();
                             }catch(SQLException ex){
                                 JOptionPane.showMessageDialog(null,ex);
                             }
                             
                             //Actualizar el stock almacen
                             Statement sto = con.createStatement();
                             ResultSet rso = sto.executeQuery("SELECT * FROM almacen WHERE codProducto = '"+(String) jTable1.getValueAt(i,0)+"'");
                             rso.last();
                             
                             int  
                                     stock = rso.getInt("stock"),
                                     cantidad = (int) jTable1.getValueAt(i,2),
                                     nuevoStock;
                             
                             nuevoStock = stock - cantidad;
                             
                             try {
                                PreparedStatement pst = con.prepareStatement("UPDATE almacen SET stock  = "+nuevoStock+" WHERE codProducto = '"+(String) jTable1.getValueAt(i,0)+"'");

                                if(pst.executeUpdate() > 0){
                                    if (i== jTable1.getRowCount()) {
                                        JOptionPane.showMessageDialog(null, "El nuevo stock del producto ha sido actualizado", "Operación Exitosa",
                                                JOptionPane.INFORMATION_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(null, "No se ha podido realizar la actualización de los datos\n"
                                                                  + "Inténtelo nuevamente.", "Error en la operación", 
                                                                  JOptionPane.ERROR_MESSAGE);
                                }
                                rso.close();
                                sto.close();
                                pst.close();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null,"Error actualizando la tabla almacen "+ex);
                            }
                            //aquí termina el codigo de actualizar stock
                             
                         }
                         
                         JOptionPane.showMessageDialog(null,"Registro guardado");
                         
                         DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
                         for (int i = 0; i < jTable1.getRowCount(); i++) {
                             tabla.removeRow(i);
                             i-=1;
                         }
                         
                         codCliente.setText("");
                         npCliente.setText("");
                         docCliente.setText("");
                         celularCliente.setText("");
                         dirCliente.setText("");
                         txt_codVendedor.setText("");
                         txt_nombreVendedor.setText("");
                         
                         //En caso de que se tenga que recoger el producto en el almacén,se guardará un registro en comprobante de pagos
                         if (recogeAlmacen.isEnabled()) {
                            CallableStatement rA = con.prepareCall("Call insertar_comprobantepago(?,?)");
                            rA.setString(1,idregistroventa);
                            rA.setString(2,"NoRegistro");
                            rA.execute();
                        }
                     } catch (SQLException e) {
//                         JOptionPane.showMessageDialog(null,"Ingrese la fecha correctamente (DD/MM/YYY)");
                         JOptionPane.showMessageDialog(null,e);
                     }
                 }
            } else {
                try {
                         CallableStatement cst = con.prepareCall("CALL insertar_registro_ventas(?,?,?,?)");
                         cst.setString(1,idcliente);
                         cst.setString(2,idvendedor);
                         cst.setString(3,fecha);
                         cst.setString(4,canc);
                         cst.execute();
                         
                         Statement st = con.createStatement();
                         ResultSet rs = st.executeQuery("SELECT * FROM registro_ventas WHERE idPersonalVentas ='"+idvendedor+"'");
                         rs.last();
                         
                         String idregistroventa = rs.getString("codRegVentas");
                         
                         for (int i = 0; i < jTable1.getRowCount(); i++) {
                             try (CallableStatement cst2 = con.prepareCall("CALL insertar_detalle_venta(?,?,?,?)")) {
                                 cst2.setString(1,idregistroventa);
                                 cst2.setString(2, (String) jTable1.getValueAt(i,0));
                                 cst2.setInt(3, (int) jTable1.getValueAt(i,2));
                                 cst2.setDouble(4,Double.parseDouble((String) jTable1.getValueAt(i,3)));
                                 cst2.execute();
                             }catch(SQLException ex){
                                 JOptionPane.showMessageDialog(null,ex);
                             }
                             
                             //Actualizar el stock almacen
                             Statement sta = con.createStatement();
                             ResultSet rsa = sta.executeQuery("SELECT * FROM almacen WHERE codProducto = '"+(String) jTable1.getValueAt(i,0)+"'");
                             rsa.last();
                             
                             int  
                                     stock = rsa.getInt("stock"),
                                     cantidad = (int) jTable1.getValueAt(i,2),
                                     nuevoStock;
                             
                             nuevoStock = stock - cantidad;
                             
                             try {
                                PreparedStatement pst = con.prepareStatement("UPDATE almacen SET stock  = "+nuevoStock+" WHERE codProducto = '"+(String) jTable1.getValueAt(i,0)+"'");

                                if(pst.executeUpdate() > 0){
                                    if (i== jTable1.getRowCount()) {
                                        JOptionPane.showMessageDialog(null, "El nuevo stock del producto ha sido actualizado", "Operación Exitosa",
                                                JOptionPane.INFORMATION_MESSAGE);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(null, "No se ha podido realizar la actualización de los datos\n"
                                                                  + "Inténtelo nuevamente.", "Error en la operación", 
                                                                  JOptionPane.ERROR_MESSAGE);
                                }

                                pst.close();
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null,"Error actualizando la tabla almacen "+ex);
                            }
                            //aquí termina el codigo de actualizar stock
                         }
                         
                         JOptionPane.showMessageDialog(null,"Registro guardado");
                         
                         DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
                         
                         for (int i = 0; i < jTable1.getRowCount(); i++) {
                             tabla.removeRow(i);
                             i-=1;
                         }
                         
                         codCliente.setText("");
                         npCliente.setText("");
                         docCliente.setText("");
                         celularCliente.setText("");
                         dirCliente.setText("");
                         txt_codVendedor.setText("");
                         txt_nombreVendedor.setText("");
                         
                         if (recogeAlmacen.isEnabled()) {
                            CallableStatement rA = con.prepareCall("Call insertar_comprobantepago(?,?)");
                            rA.setString(1,idregistroventa);
                            rA.setString(2,idcliente);
                            rA.execute();
                        }

                     } catch (SQLException e) {
//                         JOptionPane.showMessageDialog(null,"Ingrese la fecha correctamente (DD/MM/YYY)");
                         JOptionPane.showMessageDialog(null,e);
                     }
            }
            
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void totalVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalVActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Connection con;
        con = conexion.conectar();
        
        if (txt_codVendedor.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Ingrese su código");
        } else {
            try {
                String nombrePventas, apellidoPventas;
                CallableStatement cst = con.prepareCall("Call buscar_pventas(?,?,?,?,?,?)");
            
                cst.setInt(1,Integer.parseInt(txt_codVendedor.getText()));
                cst.registerOutParameter(2, java.sql.Types.INTEGER);
                cst.registerOutParameter(3, java.sql.Types.VARCHAR);
                cst.registerOutParameter(4, java.sql.Types.VARCHAR);
                cst.registerOutParameter(5, java.sql.Types.VARCHAR);
                cst.registerOutParameter(6, java.sql.Types.INTEGER);
                cst.execute();

                nombrePventas = cst.getString(5);
                apellidoPventas = cst.getString(6);
                
                txt_nombreVendedor.setText(nombrePventas + " " + apellidoPventas);
                
//                Statement st = con.createStatement();
//                ResultSet rs = st.executeQuery("SELECT * FROM empleado_almacen WHERE id_empleadoalmacen='"+txt_codVendedor.getText()+"'");
//                rs.last();
//                
//                int encontrado = rs.getRow();
//                
//                if(encontrado == 1){
//                    txt_nombreVendedor.setText(rs.getString("nombre")+ " " +rs.getString("apellido"));
//                }else{
//                    try {
//                        Statement st2 = con.createStatement();
//                        ResultSet rs2 = st2.executeQuery("SELECT * FROM vendedor WHERE id_empleado='"+txt_codVendedor.getText()+"'");
//                        rs2.last();
//
//                        int encontrado2 = rs2.getRow();
//
//                        if (encontrado2==1) {
//                            txt_nombreVendedor.setText(rs2.getString("nombre")+ " " +rs2.getString("apellido"));
//
//                        } else {
//                            JOptionPane.showMessageDialog(null,"Usuario inexistente");
//                        }
//                        rs2.close();
//                        st.close();
//                    } catch (SQLException e) {
//                        JOptionPane.showMessageDialog(null,e);
//                    }
//                }
//                rs.close();
//                st.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double montotal = 0, totaligv, total, descuento;
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            double
                    nuevovalor = Double.parseDouble((String) jTable1.getValueAt(i,4));
            
            montotal +=  nuevovalor;
        }
        
        jTextField1.setText(Double.toString(Math.round(montotal*100)/100));
        
        totaligv = montotal * Double.parseDouble(jTextField12.getText())/100;
        descuento = montotal * Double.parseDouble(jTextField2.getText())/100;
        total = montotal + totaligv - descuento;

        igv.setText(Double.toString(Math.round(totaligv*100)/100));
        totalV.setText(Double.toString(Math.round(total*100)/100));
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNota;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private static javax.swing.JButton btnNuevo;
    private javax.swing.JTextField celularCliente;
    private javax.swing.JTextField codCliente;
    private javax.swing.JTextField dirCliente;
    private javax.swing.JTextField docCliente;
    public static javax.swing.JTextField idProducto;
    private javax.swing.JTextField igv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JSpinner jSpinner2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField npCliente;
    private javax.swing.JTextField numeroventa;
    public javax.swing.JTextField precioProducto;
    private javax.swing.JCheckBox recogeAlmacen;
    private javax.swing.JTextField totalV;
    private javax.swing.JTextField txt_codVendedor;
    private javax.swing.JTextField txt_nombreVendedor;
    // End of variables declaration//GEN-END:variables
public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }
}
