/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios_secundarios;

import conexion.conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GynRaider
 */
public class registroProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form registroProducto
     */
    
    String codProd,nomb,marc,pre;

    public registroProducto() {
        initComponents();
                jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = jTable1.rowAtPoint(e.getPoint());
                int columna = jTable1.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
//                    System.out.println(jTable1.getValueAt(fila, columna));
                    codProd = jTable1.getValueAt(fila,0).toString();
                    nomb = jTable1.getValueAt(fila,1).toString();
                    marc = jTable1.getValueAt(fila,2).toString();
                    pre = jTable1.getValueAt(fila,3).toString();
                }
            }
        });
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 11, -1, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 11, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Marca", "Precio", "Stock", "Numero Almacen"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 563, 230));

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/Captura.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection con;
        con = conexion.conectar();
        ResultSet r;

        String 
                codProducto,
                nombre,
                marca,
                numeroAlmacen;
        int
                stock;
        
        double precio;
        DefaultTableModel tabla= (DefaultTableModel) jTable1.getModel();
                
        for (int i = 0; i < jTable1.getRowCount(); i++) {
             tabla.removeRow(i);
             i-=1;
         }
        
       try{

           CallableStatement cts = con.prepareCall("CALL mostrar_producto_almacen");
           r=cts.executeQuery();
           
           while (r.next()){
               codProducto=r.getString("codProducto");
               nombre=r.getString("nombre");
               marca=r.getString("marca");
               precio = r.getDouble("precio");
               stock = r.getInt("stock");
               numeroAlmacen = r.getString("numeroAlmacen");
              
               tabla.addRow( new Object[] {codProducto, nombre, marca, precio,stock,numeroAlmacen} );
            }

       }catch (Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        nuevasVentas nv = new nuevasVentas();
        
//        JOptionPane.showMessageDialog(null,codProd+nomb+marc+pre);
//        nuevasVentas.jTextField3.setText(codProd);

        DefaultTableModel tabla = (DefaultTableModel)nuevasVentas.jTable1.getModel();
        tabla.addRow(new Object[]{codProd,nomb,"sdf",pre,"eefef"});
//        nuevasVentas.jTable1.setModel(model);
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
